import { Recipe, MealPlanDay } from '@/types';
import { uid } from '@/utils';

const images = {
  grilledChicken: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=600&h=400&fit=crop',
  pasta: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=400&fit=crop',
  salad: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=400&fit=crop',
  smoothie: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=600&h=400&fit=crop',
  stirFry: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
  soup: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=400&fit=crop',
  tacos: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop',
  omelette: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop',
  salmon: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&h=400&fit=crop',
  curry: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
  pancakes: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=600&h=400&fit=crop',
  buddha: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=400&fit=crop',
};

export const mockRecipes: Recipe[] = [
  {
    id: uid(),
    title: 'Grilled Lemon Herb Chicken',
    description: 'Juicy grilled chicken breast marinated in a bright lemon-herb mixture with roasted vegetables. Perfect for a high-protein dinner that is ready in under 30 minutes.',
    image: images.grilledChicken,
    cookingTime: 25,
    prepTime: 10,
    difficulty: 'Easy',
    servings: 2,
    calories: 380,
    protein: 42,
    carbs: 12,
    fat: 18,
    ingredients: [
      { name: 'Chicken breast', amount: '2', unit: 'pieces' },
      { name: 'Lemon', amount: '1', unit: 'whole' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Garlic', amount: '3', unit: 'cloves' },
      { name: 'Fresh rosemary', amount: '2', unit: 'sprigs' },
      { name: 'Fresh thyme', amount: '3', unit: 'sprigs' },
      { name: 'Salt', amount: '1', unit: 'tsp' },
      { name: 'Black pepper', amount: '½', unit: 'tsp' },
      { name: 'Zucchini', amount: '1', unit: 'medium' },
      { name: 'Bell pepper', amount: '1', unit: 'large' },
    ],
    instructions: [
      'Mix olive oil, lemon juice, minced garlic, chopped rosemary, and thyme in a bowl.',
      'Season chicken breasts with salt and pepper, then coat with the marinade. Let sit for 10 minutes.',
      'Preheat grill or grill pan to medium-high heat.',
      'Slice zucchini and bell pepper into thick strips and toss with a little olive oil.',
      'Grill chicken for 6-7 minutes per side until internal temp reaches 165°F.',
      'Grill vegetables alongside for 4-5 minutes until charred and tender.',
      'Let chicken rest for 3 minutes, then slice and serve with grilled vegetables.',
    ],
    dietaryTags: ['High Protein', 'Gluten-Free', 'Low Carb', 'Keto-Friendly'],
    cuisineType: 'Mediterranean',
    aiTip: 'Pound the chicken to even thickness before marinating for perfectly uniform cooking — no dry edges!',
    aiMatchScore: 95,
    matchReasons: ['High Protein', 'Under 400 Calories', 'Ready in 25 Minutes'],
    aiInsights: [
      { type: 'nutrition', title: 'Protein Powerhouse', content: 'This meal packs 42g of lean protein, perfect for muscle recovery and keeping you full longer.' },
      { type: 'substitution', title: 'Swap Chicken', content: 'Try tofu or tempeh for a plant-based version with similar protein content.' },
      { type: 'tip', title: 'Flavor Boost', content: 'Add a pinch of smoked paprika to the marinade for a subtle smoky depth.' },
    ],
  },
  {
    id: uid(),
    title: 'Creamy Garlic Tuscan Pasta',
    description: 'Rich and creamy pasta with sun-dried tomatoes, spinach, and a luxurious garlic parmesan sauce. Restaurant-quality comfort food made at home.',
    image: images.pasta,
    cookingTime: 20,
    prepTime: 5,
    difficulty: 'Easy',
    servings: 4,
    calories: 520,
    protein: 18,
    carbs: 58,
    fat: 24,
    ingredients: [
      { name: 'Penne pasta', amount: '400', unit: 'g' },
      { name: 'Heavy cream', amount: '1', unit: 'cup' },
      { name: 'Parmesan cheese', amount: '½', unit: 'cup' },
      { name: 'Garlic', amount: '4', unit: 'cloves' },
      { name: 'Sun-dried tomatoes', amount: '½', unit: 'cup' },
      { name: 'Fresh spinach', amount: '2', unit: 'cups' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Italian seasoning', amount: '1', unit: 'tsp' },
      { name: 'Salt and pepper', amount: '', unit: 'to taste' },
    ],
    instructions: [
      'Cook penne in salted boiling water according to package directions. Reserve 1 cup pasta water before draining.',
      'In a large skillet, heat olive oil over medium heat. Add minced garlic and cook for 30 seconds until fragrant.',
      'Add sun-dried tomatoes and cook for 2 minutes.',
      'Pour in heavy cream and bring to a gentle simmer. Add Italian seasoning.',
      'Stir in parmesan cheese until melted and smooth.',
      'Add spinach and cook until wilted, about 1-2 minutes.',
      'Toss in drained pasta, adding pasta water as needed for desired consistency.',
      'Season with salt and pepper, serve immediately with extra parmesan.',
    ],
    dietaryTags: ['Vegetarian', 'Comfort Food'],
    cuisineType: 'Italian',
    aiTip: 'Reserve that pasta water — the starch is liquid gold for making silky, clingy sauces.',
    aiMatchScore: 88,
    matchReasons: ['Vegetarian', 'Quick & Easy', 'Comfort Food'],
    aiInsights: [
      { type: 'nutrition', title: 'Energy Dense', content: 'Great pre-workout meal with complex carbs for sustained energy.' },
      { type: 'healthier', title: 'Lighter Version', content: 'Swap heavy cream for cashew cream and use whole wheat pasta for a healthier twist.' },
    ],
  },
  {
    id: uid(),
    title: 'Asian Sesame Chicken Stir Fry',
    description: 'Vibrant stir-fry with tender chicken, crisp vegetables, and a sticky sesame-soy glaze. Healthier than takeout and done in 20 minutes.',
    image: images.stirFry,
    cookingTime: 20,
    prepTime: 10,
    difficulty: 'Easy',
    servings: 3,
    calories: 410,
    protein: 35,
    carbs: 28,
    fat: 16,
    ingredients: [
      { name: 'Chicken thigh', amount: '500', unit: 'g' },
      { name: 'Broccoli florets', amount: '2', unit: 'cups' },
      { name: 'Bell pepper', amount: '1', unit: 'large' },
      { name: 'Soy sauce', amount: '3', unit: 'tbsp' },
      { name: 'Sesame oil', amount: '1', unit: 'tbsp' },
      { name: 'Honey', amount: '2', unit: 'tbsp' },
      { name: 'Rice vinegar', amount: '1', unit: 'tbsp' },
      { name: 'Cornstarch', amount: '1', unit: 'tbsp' },
      { name: 'Sesame seeds', amount: '1', unit: 'tbsp' },
      { name: 'Green onion', amount: '2', unit: 'stalks' },
      { name: 'Ginger', amount: '1', unit: 'inch' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
    ],
    instructions: [
      'Slice chicken into bite-sized pieces. Toss with 1 tbsp soy sauce and cornstarch.',
      'Mix remaining soy sauce, sesame oil, honey, and rice vinegar for the glaze.',
      'Heat a wok or large skillet over high heat with a little oil.',
      'Stir-fry chicken until golden brown, about 4-5 minutes. Remove and set aside.',
      'Add broccoli and bell pepper. Stir-fry for 3 minutes until crisp-tender.',
      'Return chicken to the wok. Pour in the glaze and toss to coat.',
      'Cook for 1-2 minutes until sauce thickens and glazes everything.',
      'Garnish with sesame seeds and sliced green onion. Serve over rice.',
    ],
    dietaryTags: ['High Protein', 'Dairy-Free'],
    cuisineType: 'Asian',
    aiTip: 'Use the highest heat your stove can manage — the secret to restaurant-quality stir fry is wok hei (breath of the wok).',
    aiMatchScore: 92,
    matchReasons: ['High Protein', 'Under 500 Calories', 'Quick Prep'],
    aiInsights: [
      { type: 'tip', title: 'Prep Everything First', content: 'Stir fry moves fast. Have all veggies cut, sauce mixed, and chicken ready before turning on the heat.' },
      { type: 'substitution', title: 'Make It Vegan', content: 'Swap chicken for extra-firm tofu, pressed and cubed. Use tamari instead of soy sauce for gluten-free.' },
    ],
  },
  {
    id: uid(),
    title: 'Mediterranean Quinoa Buddha Bowl',
    description: 'A nourishing bowl packed with quinoa, roasted chickpeas, fresh veggies, hummus, and a zesty lemon-tahini dressing.',
    image: images.buddha,
    cookingTime: 30,
    prepTime: 10,
    difficulty: 'Easy',
    servings: 2,
    calories: 450,
    protein: 18,
    carbs: 52,
    fat: 20,
    ingredients: [
      { name: 'Quinoa', amount: '1', unit: 'cup' },
      { name: 'Chickpeas (canned)', amount: '1', unit: 'can' },
      { name: 'Cucumber', amount: '1', unit: 'medium' },
      { name: 'Cherry tomatoes', amount: '1', unit: 'cup' },
      { name: 'Red onion', amount: '¼', unit: 'medium' },
      { name: 'Hummus', amount: '4', unit: 'tbsp' },
      { name: 'Tahini', amount: '2', unit: 'tbsp' },
      { name: 'Lemon', amount: '1', unit: 'whole' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Paprika', amount: '1', unit: 'tsp' },
      { name: 'Feta cheese', amount: '¼', unit: 'cup', optional: true },
    ],
    instructions: [
      'Cook quinoa according to package directions and let cool slightly.',
      'Drain and rinse chickpeas. Toss with olive oil, paprika, salt, and pepper.',
      'Roast chickpeas at 400°F for 20-25 minutes until crispy.',
      'Dice cucumber, halve cherry tomatoes, and thinly slice red onion.',
      'Whisk tahini, lemon juice, a splash of water, salt, and garlic for dressing.',
      'Assemble bowls: quinoa base, arrange veggies, top with crispy chickpeas.',
      'Dollop hummus on the side, drizzle tahini dressing, and crumble feta if using.',
    ],
    dietaryTags: ['Vegetarian', 'Vegan Option', 'Gluten-Free', 'Meal Prep'],
    cuisineType: 'Mediterranean',
    aiTip: 'Make extra crispy chickpeas — they store in an airtight container for 3 days and are amazing as snacks.',
    aiMatchScore: 90,
    matchReasons: ['Vegetarian', 'Balanced Macros', 'Meal Prep Friendly'],
    aiInsights: [
      { type: 'nutrition', title: 'Complete Protein', content: 'Quinoa + chickpeas form a complete plant protein with all essential amino acids.' },
      { type: 'healthier', title: 'Lower Calorie', content: 'Skip the feta and use less tahini dressing to bring this down to 380 calories.' },
    ],
  },
  {
    id: uid(),
    title: 'Spicy Thai Coconut Soup',
    description: 'Aromatic coconut soup infused with lemongrass, galangal, and chili. Loaded with mushrooms, shrimp, and fresh herbs.',
    image: images.soup,
    cookingTime: 25,
    prepTime: 15,
    difficulty: 'Medium',
    servings: 4,
    calories: 320,
    protein: 24,
    carbs: 16,
    fat: 20,
    ingredients: [
      { name: 'Coconut milk', amount: '2', unit: 'cans' },
      { name: 'Shrimp', amount: '300', unit: 'g' },
      { name: 'Mushrooms', amount: '200', unit: 'g' },
      { name: 'Lemongrass', amount: '2', unit: 'stalks' },
      { name: 'Fish sauce', amount: '2', unit: 'tbsp' },
      { name: 'Lime', amount: '2', unit: 'whole' },
      { name: 'Thai chili', amount: '2', unit: 'pieces' },
      { name: 'Fresh cilantro', amount: '¼', unit: 'cup' },
      { name: 'Ginger', amount: '1', unit: 'inch' },
      { name: 'Chicken broth', amount: '1', unit: 'cup' },
    ],
    instructions: [
      'Bruise lemongrass stalks and slice. Slice ginger and chili.',
      'Bring chicken broth to simmer. Add lemongrass, ginger, and chili. Cook 5 minutes.',
      'Add coconut milk and bring to a gentle simmer.',
      'Add sliced mushrooms and cook for 3 minutes.',
      'Add shrimp and cook until pink, about 3-4 minutes.',
      'Season with fish sauce and lime juice. Taste and adjust.',
      'Serve hot, garnished with fresh cilantro and lime wedges.',
    ],
    dietaryTags: ['Gluten-Free', 'Dairy-Free', 'Low Carb'],
    cuisineType: 'Thai',
    aiTip: 'Don\'t boil the coconut milk vigorously — gentle simmering keeps it smooth and prevents separation.',
    aiMatchScore: 85,
    matchReasons: ['Low Carb', 'Under 350 Calories', 'Warming & Comforting'],
    aiInsights: [
      { type: 'tip', title: 'Heat Control', content: 'Add chili gradually. You can always add more, but you can\'t take it back!' },
      { type: 'substitution', title: 'Make It Vegan', content: 'Replace shrimp with tofu and use soy sauce instead of fish sauce.' },
    ],
  },
  {
    id: uid(),
    title: 'Classic Fluffy Pancakes',
    description: 'Light, fluffy buttermilk pancakes with a golden crust. Serve with maple syrup, fresh berries, and a pat of butter.',
    image: images.pancakes,
    cookingTime: 15,
    prepTime: 5,
    difficulty: 'Easy',
    servings: 4,
    calories: 350,
    protein: 10,
    carbs: 48,
    fat: 14,
    ingredients: [
      { name: 'All-purpose flour', amount: '1½', unit: 'cups' },
      { name: 'Buttermilk', amount: '1¼', unit: 'cups' },
      { name: 'Egg', amount: '1', unit: 'large' },
      { name: 'Butter (melted)', amount: '3', unit: 'tbsp' },
      { name: 'Sugar', amount: '2', unit: 'tbsp' },
      { name: 'Baking powder', amount: '1½', unit: 'tsp' },
      { name: 'Baking soda', amount: '½', unit: 'tsp' },
      { name: 'Vanilla extract', amount: '1', unit: 'tsp' },
      { name: 'Salt', amount: '¼', unit: 'tsp' },
    ],
    instructions: [
      'Whisk flour, sugar, baking powder, baking soda, and salt in a large bowl.',
      'In a separate bowl, whisk buttermilk, egg, melted butter, and vanilla.',
      'Pour wet ingredients into dry. Stir until just combined — lumps are okay!',
      'Let batter rest for 5 minutes while you heat a griddle to medium.',
      'Lightly butter the griddle. Pour ¼ cup batter per pancake.',
      'Cook until bubbles form on surface and edges look set, about 2-3 minutes.',
      'Flip and cook 1-2 more minutes until golden. Serve immediately.',
    ],
    dietaryTags: ['Vegetarian', 'Breakfast', 'Comfort Food'],
    cuisineType: 'American',
    aiTip: 'The #1 secret: do NOT overmix the batter. Those lumps create air pockets that make pancakes fluffy.',
    aiMatchScore: 78,
    matchReasons: ['Quick Breakfast', 'Easy', 'Family Favorite'],
    aiInsights: [
      { type: 'nutrition', title: 'Weekend Treat', content: 'Best enjoyed as an occasional treat. The carb-protein ratio makes this ideal fuel before a workout.' },
      { type: 'healthier', title: 'Protein Boost', content: 'Add a scoop of protein powder and use Greek yogurt instead of buttermilk for 25g+ protein.' },
    ],
  },
  {
    id: uid(),
    title: 'Honey Glazed Salmon',
    description: 'Perfectly seared salmon with a sticky honey-soy glaze, served with steamed broccoli and jasmine rice.',
    image: images.salmon,
    cookingTime: 20,
    prepTime: 5,
    difficulty: 'Medium',
    servings: 2,
    calories: 480,
    protein: 38,
    carbs: 30,
    fat: 22,
    ingredients: [
      { name: 'Salmon fillet', amount: '2', unit: 'pieces' },
      { name: 'Honey', amount: '2', unit: 'tbsp' },
      { name: 'Soy sauce', amount: '2', unit: 'tbsp' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
      { name: 'Ginger', amount: '1', unit: 'tsp' },
      { name: 'Sesame oil', amount: '1', unit: 'tsp' },
      { name: 'Jasmine rice', amount: '1', unit: 'cup' },
      { name: 'Broccoli', amount: '2', unit: 'cups' },
      { name: 'Lime', amount: '1', unit: 'whole' },
    ],
    instructions: [
      'Mix honey, soy sauce, minced garlic, ginger, and sesame oil for the glaze.',
      'Cook jasmine rice according to package directions.',
      'Pat salmon dry and season with salt and pepper.',
      'Heat an oven-safe skillet over medium-high. Sear salmon skin-side up for 3 minutes.',
      'Flip salmon, pour glaze over, and transfer to 400°F oven for 8-10 minutes.',
      'Steam broccoli until bright green and tender, about 4 minutes.',
      'Plate rice, top with salmon, drizzle remaining glaze, serve with broccoli and lime.',
    ],
    dietaryTags: ['High Protein', 'Omega-3 Rich', 'Dairy-Free'],
    cuisineType: 'Asian Fusion',
    aiTip: 'Start skin-side up in the pan so the flesh gets a gorgeous sear, then flip so skin crisps in the oven.',
    aiMatchScore: 91,
    matchReasons: ['High Protein', 'Omega-3', 'Balanced Meal'],
    aiInsights: [
      { type: 'nutrition', title: 'Brain Food', content: 'Wild salmon provides 1.5g omega-3 fatty acids per serving — essential for brain health.' },
      { type: 'tip', title: 'Perfect Doneness', content: 'Salmon is best at 125°F internal temp for medium. It will carry over 5°F while resting.' },
    ],
  },
  {
    id: uid(),
    title: 'Street-Style Chicken Tacos',
    description: 'Zesty lime-chili chicken tacos with quick pickled onions, fresh cilantro, and creamy avocado crema.',
    image: images.tacos,
    cookingTime: 20,
    prepTime: 15,
    difficulty: 'Easy',
    servings: 4,
    calories: 420,
    protein: 30,
    carbs: 34,
    fat: 18,
    ingredients: [
      { name: 'Chicken thigh', amount: '500', unit: 'g' },
      { name: 'Corn tortillas', amount: '8', unit: 'small' },
      { name: 'Lime', amount: '2', unit: 'whole' },
      { name: 'Chili powder', amount: '1', unit: 'tbsp' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Avocado', amount: '1', unit: 'large' },
      { name: 'Sour cream', amount: '¼', unit: 'cup' },
      { name: 'Red onion', amount: '1', unit: 'small' },
      { name: 'Fresh cilantro', amount: '½', unit: 'cup' },
      { name: 'Garlic', amount: '2', unit: 'cloves' },
    ],
    instructions: [
      'Season chicken with chili powder, cumin, garlic, lime juice, salt, and pepper.',
      'Quick pickle red onion: thinly slice and soak in lime juice with a pinch of salt.',
      'Blend avocado, sour cream, lime juice, and salt for the crema.',
      'Grill or pan-sear chicken over high heat for 5-6 minutes per side.',
      'Rest chicken 5 minutes, then slice against the grain.',
      'Warm tortillas in a dry skillet for 30 seconds per side.',
      'Assemble tacos: tortilla, chicken, pickled onions, avocado crema, cilantro.',
    ],
    dietaryTags: ['High Protein', 'Gluten-Free Option'],
    cuisineType: 'Mexican',
    aiTip: 'Double-stack your corn tortillas — street taco style. They hold up better and taste more authentic.',
    aiMatchScore: 87,
    matchReasons: ['Family Friendly', 'Quick', 'High Protein'],
    aiInsights: [
      { type: 'tip', title: 'Char Matters', content: 'Get a good char on the chicken — those caramelized bits are where all the flavor lives.' },
      { type: 'substitution', title: 'Fish Tacos', content: 'Swap chicken for grilled white fish and add shredded cabbage for a coastal twist.' },
    ],
  },
  {
    id: uid(),
    title: 'Veggie Spinach Omelette',
    description: 'Fluffy three-egg omelette loaded with sautéed spinach, mushrooms, bell peppers, and melted cheese.',
    image: images.omelette,
    cookingTime: 10,
    prepTime: 5,
    difficulty: 'Easy',
    servings: 1,
    calories: 320,
    protein: 24,
    carbs: 8,
    fat: 22,
    ingredients: [
      { name: 'Eggs', amount: '3', unit: 'large' },
      { name: 'Baby spinach', amount: '1', unit: 'cup' },
      { name: 'Mushrooms', amount: '4', unit: 'medium' },
      { name: 'Bell pepper', amount: '¼', unit: 'medium' },
      { name: 'Cheese (cheddar or gruyere)', amount: '¼', unit: 'cup' },
      { name: 'Butter', amount: '1', unit: 'tbsp' },
      { name: 'Salt', amount: '', unit: 'to taste' },
      { name: 'Black pepper', amount: '', unit: 'to taste' },
    ],
    instructions: [
      'Beat eggs with a pinch of salt and pepper until just combined.',
      'Sauté sliced mushrooms and diced bell pepper in butter for 3 minutes.',
      'Add spinach and cook until wilted, about 1 minute. Remove veggies from pan.',
      'Add a little more butter to the same pan over medium-low heat.',
      'Pour in eggs and let set at the edges for 30 seconds.',
      'Gently push edges inward, tilting pan to let raw egg flow to edges.',
      'When mostly set but still creamy on top, add veggies and cheese to one half.',
      'Fold omelette in half and slide onto plate. Let rest 1 minute before serving.',
    ],
    dietaryTags: ['High Protein', 'Low Carb', 'Keto', 'Vegetarian', 'Breakfast'],
    cuisineType: 'French',
    aiTip: 'Low and slow is the French way — medium-low heat gives you a creamy, custardy interior instead of a rubbery one.',
    aiMatchScore: 93,
    matchReasons: ['High Protein', 'Low Carb', 'Under 10 Minutes'],
    aiInsights: [
      { type: 'nutrition', title: 'Keto Champion', content: 'Only 8g carbs with 24g protein — ideal for keto and low-carb diets.' },
      { type: 'tip', title: 'The Perfect Fold', content: 'Use a rubber spatula and tilt the pan toward your plate for a seamless fold every time.' },
    ],
  },
  {
    id: uid(),
    title: 'Golden Chickpea Curry',
    description: 'Creamy, aromatic chickpea curry with coconut milk, spinach, and warming Indian spices. Comforting, healthy, and completely plant-based.',
    image: images.curry,
    cookingTime: 30,
    prepTime: 10,
    difficulty: 'Easy',
    servings: 4,
    calories: 380,
    protein: 14,
    carbs: 42,
    fat: 18,
    ingredients: [
      { name: 'Chickpeas (canned)', amount: '2', unit: 'cans' },
      { name: 'Coconut milk', amount: '1', unit: 'can' },
      { name: 'Diced tomatoes', amount: '1', unit: 'can' },
      { name: 'Onion', amount: '1', unit: 'large' },
      { name: 'Garlic', amount: '4', unit: 'cloves' },
      { name: 'Ginger', amount: '1', unit: 'inch' },
      { name: 'Spinach', amount: '3', unit: 'cups' },
      { name: 'Curry powder', amount: '2', unit: 'tbsp' },
      { name: 'Turmeric', amount: '1', unit: 'tsp' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Garam masala', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Dice onion. Mince garlic and ginger.',
      'Sauté onion in oil over medium heat for 5 minutes until soft.',
      'Add garlic, ginger, curry powder, turmeric, and cumin. Cook 1 minute until fragrant.',
      'Add diced tomatoes and coconut milk. Stir and bring to a simmer.',
      'Drain and rinse chickpeas. Add to the pot.',
      'Simmer uncovered for 15 minutes until sauce thickens.',
      'Stir in spinach and garam masala. Cook 2 more minutes.',
      'Season with salt and serve over basmati rice or with naan bread.',
    ],
    dietaryTags: ['Vegan', 'Gluten-Free', 'High Fiber', 'Meal Prep'],
    cuisineType: 'Indian',
    aiTip: 'Bloom your spices in oil before adding liquid — this releases fat-soluble flavor compounds that water can\'t unlock.',
    aiMatchScore: 86,
    matchReasons: ['Vegan', 'High Fiber', 'Meal Prep Friendly'],
    aiInsights: [
      { type: 'nutrition', title: 'Fiber Rich', content: 'Chickpeas provide 12g fiber per cup — nearly half your daily needs.' },
      { type: 'healthier', title: 'Reduce Fat', content: 'Use light coconut milk to cut 100 calories per serving without losing creaminess.' },
    ],
  },
  {
    id: uid(),
    title: 'Berry Protein Smoothie Bowl',
    description: 'Thick, creamy acai-berry smoothie bowl topped with granola, fresh fruit, coconut flakes, and a drizzle of honey.',
    image: images.smoothie,
    cookingTime: 5,
    prepTime: 5,
    difficulty: 'Easy',
    servings: 1,
    calories: 380,
    protein: 28,
    carbs: 52,
    fat: 8,
    ingredients: [
      { name: 'Frozen mixed berries', amount: '1', unit: 'cup' },
      { name: 'Frozen banana', amount: '1', unit: 'medium' },
      { name: 'Protein powder (vanilla)', amount: '1', unit: 'scoop' },
      { name: 'Greek yogurt', amount: '½', unit: 'cup' },
      { name: 'Almond milk', amount: '¼', unit: 'cup' },
      { name: 'Granola', amount: '¼', unit: 'cup' },
      { name: 'Fresh berries', amount: '¼', unit: 'cup' },
      { name: 'Coconut flakes', amount: '1', unit: 'tbsp' },
      { name: 'Honey', amount: '1', unit: 'tsp' },
      { name: 'Chia seeds', amount: '1', unit: 'tsp' },
    ],
    instructions: [
      'Add frozen berries, banana, protein powder, Greek yogurt, and almond milk to a blender.',
      'Blend until thick and smooth — it should be thicker than a regular smoothie.',
      'Pour into a bowl.',
      'Arrange toppings: granola, fresh berries, coconut flakes, chia seeds.',
      'Drizzle with honey and serve immediately.',
    ],
    dietaryTags: ['High Protein', 'Vegetarian', 'Breakfast', 'Post-Workout'],
    cuisineType: 'Health Food',
    aiTip: 'Use as little liquid as possible for the thickest consistency — you eat this with a spoon, not a straw!',
    aiMatchScore: 82,
    matchReasons: ['High Protein', 'Quick Breakfast', 'Post-Workout'],
    aiInsights: [
      { type: 'nutrition', title: 'Recovery Fuel', content: '28g protein with fast-digesting carbs — optimal 30-minute post-workout window nutrition.' },
      { type: 'substitution', title: 'Dairy-Free', content: 'Use coconut yogurt and plant-based protein for a fully vegan version.' },
    ],
  },
  {
    id: uid(),
    title: 'Rainbow Superfood Salad',
    description: 'A vibrant, nutrient-packed salad with kale, quinoa, avocado, beets, carrots, edamame, and a citrus-miso dressing.',
    image: images.salad,
    cookingTime: 15,
    prepTime: 15,
    difficulty: 'Easy',
    servings: 2,
    calories: 340,
    protein: 16,
    carbs: 38,
    fat: 16,
    ingredients: [
      { name: 'Kale', amount: '4', unit: 'cups' },
      { name: 'Cooked quinoa', amount: '1', unit: 'cup' },
      { name: 'Avocado', amount: '1', unit: 'medium' },
      { name: 'Cooked beets', amount: '1', unit: 'cup' },
      { name: 'Shredded carrots', amount: '½', unit: 'cup' },
      { name: 'Edamame', amount: '½', unit: 'cup' },
      { name: 'Pumpkin seeds', amount: '2', unit: 'tbsp' },
      { name: 'White miso paste', amount: '1', unit: 'tbsp' },
      { name: 'Orange juice', amount: '2', unit: 'tbsp' },
      { name: 'Rice vinegar', amount: '1', unit: 'tbsp' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
    ],
    instructions: [
      'Massage kale with a drizzle of olive oil and pinch of salt for 2 minutes until tender.',
      'Whisk miso paste, orange juice, rice vinegar, and olive oil for the dressing.',
      'Arrange massaged kale as the base in serving bowls.',
      'Top with quinoa, diced beets, shredded carrots, and edamame in sections.',
      'Slice avocado and fan on top.',
      'Sprinkle pumpkin seeds over the salad.',
      'Drizzle citrus-miso dressing and serve.',
    ],
    dietaryTags: ['Vegan', 'Gluten-Free', 'Superfood', 'High Fiber'],
    cuisineType: 'Health Food',
    aiTip: 'Massaging kale breaks down the tough cellulose, turning it from bitter and chewy to silky and sweet.',
    aiMatchScore: 84,
    matchReasons: ['Vegan', 'Nutrient Dense', 'Under 350 Calories'],
    aiInsights: [
      { type: 'nutrition', title: 'Rainbow Nutrition', content: 'Each color represents different phytonutrients — eating the rainbow ensures diverse micronutrient intake.' },
      { type: 'tip', title: 'Meal Prep Champion', content: 'Prep everything except avocado on Sunday. The kale actually improves after marinating in dressing overnight.' },
    ],
  },
];

export const trendingSearches = [
  'High protein dinner under 500 calories',
  'Easy vegetarian meal for tonight',
  'Quick chicken recipes under 20 minutes',
  'Healthy meal prep for the week',
  'Comfort food for rainy weather',
  'Low carb lunch ideas',
  'Keto breakfast recipes',
  'One-pot meals for busy weeknights',
];

export const quickIngredients = [
  'Chicken', 'Eggs', 'Rice', 'Spinach', 'Tomatoes', 'Pasta',
  'Salmon', 'Avocado', 'Broccoli', 'Tofu', 'Chickpeas', 'Garlic',
];

export const dietaryOptions = [
  'Vegetarian', 'Vegan', 'Gluten-Free', 'Dairy-Free', 'Keto',
  'Low Carb', 'High Protein', 'Paleo', 'Whole30',
];

export const difficultyOptions = ['Easy', 'Medium', 'Hard'] as const;

export const cuisineOptions = [
  'Italian', 'Mexican', 'Asian', 'Mediterranean', 'Indian',
  'Thai', 'American', 'French', 'Japanese', 'Middle Eastern',
];

export const mockMealPlan: MealPlanDay[] = [
  {
    day: 'Monday',
    breakfast: mockRecipes[5],
    lunch: mockRecipes[11],
    dinner: mockRecipes[0],
  },
  {
    day: 'Tuesday',
    breakfast: mockRecipes[8],
    lunch: mockRecipes[3],
    dinner: mockRecipes[2],
  },
  {
    day: 'Wednesday',
    breakfast: mockRecipes[10],
    lunch: mockRecipes[7],
    dinner: mockRecipes[6],
  },
  {
    day: 'Thursday',
    breakfast: mockRecipes[8],
    lunch: mockRecipes[9],
    dinner: mockRecipes[1],
  },
  {
    day: 'Friday',
    breakfast: mockRecipes[5],
    lunch: mockRecipes[3],
    dinner: mockRecipes[4],
  },
  {
    day: 'Saturday',
    breakfast: mockRecipes[10],
    lunch: mockRecipes[11],
    dinner: mockRecipes[7],
  },
  {
    day: 'Sunday',
    breakfast: mockRecipes[5],
    lunch: mockRecipes[1],
    dinner: mockRecipes[6],
  },
];
