import React, { useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { FiDownload, FiRefreshCw } from 'react-icons/fi';
import { HiSparkles } from 'react-icons/hi2';
import { PageWrapper } from '@/components/layout/PageWrapper';
import { Button } from '@/components/ui/Button';
import { ErrorState } from '@/components/ui/ErrorState';
import { MealPlanForm } from '@/components/meal-planner/MealPlanForm';
import { MealPlanDayTabs } from '@/components/meal-planner/MealPlanDayTabs';
import { MealPlanDayDetail } from '@/components/meal-planner/MealPlanDayDetail';
import { MealPlanWeekGrid } from '@/components/meal-planner/MealPlanWeekGrid';
import { streamMealPlan } from '@/services/aiService';
import { mockMealPlan } from '@/services/mockData';
import { exportMealPlanPDF } from '@/utils/exportPDF';
import type { MealPlanDay, Recipe } from '@/types';
import './MealPlanner.css';

export const MealPlanner: React.FC = () => {
  const navigate = useNavigate();
  const [preferences, setPreferences] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [mealPlan, setMealPlan] = useState<MealPlanDay[]>(mockMealPlan);
  const [selectedDay, setSelectedDay] = useState<string>(mockMealPlan[0]?.day || 'Monday');
  const [planError, setPlanError] = useState<string | null>(null);
  const [lastPref, setLastPref] = useState('');
  const abortRef = useRef<AbortController | null>(null);

  const handleGenerate = async (pref?: string) => {
    const usedPref = pref ?? preferences;
    setLastPref(usedPref);

    // Cancel any in-flight generation
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    setIsGenerating(true);
    setPlanError(null);

    try {
      let firstYield = true;
      for await (const days of streamMealPlan(usedPref || undefined, controller.signal)) {
        if (controller.signal.aborted) return;
        if (firstYield) {
          firstYield = false;
          setSelectedDay(days[0]?.day || 'Monday');
        }
        setMealPlan(days);
      }
      if (!controller.signal.aborted) {
        toast.success('AI Meal Plan generated!');
        setIsGenerating(false);
      }
    } catch (err) {
      if (controller.signal.aborted) return;
      console.error(err);
      setPlanError(
        'Failed to generate your meal plan. This may be due to an API configuration issue or network error.'
      );
      setMealPlan(mockMealPlan);
      setIsGenerating(false);
    }
  };

  const handleSlotClick = (recipe: Recipe | null) => {
    if (recipe) navigate(`/recipe/${recipe.id}`);
    else navigate('/recommendations');
  };

  const getDayTotal = (day: MealPlanDay) =>
    (day.breakfast?.calories ?? 0) + (day.lunch?.calories ?? 0) + (day.dinner?.calories ?? 0);

  const getDayProtein = (day: MealPlanDay) =>
    (day.breakfast?.protein ?? 0) + (day.lunch?.protein ?? 0) + (day.dinner?.protein ?? 0);

  const selectedDayData = mealPlan.find((d) => d.day === selectedDay);

  return (
    <PageWrapper className="planner-page">
      <div className="planner-header">
        <div className="planner-header__left">
          <div className="planner-header__eyebrow">
            <HiSparkles />
            AI-Generated Plan
          </div>
          <h1 className="planner-header__title">Weekly Meal Planner</h1>
          <p className="planner-header__desc">
            Personalised 7-day plans generated by AI based on your goals and preferences.
          </p>
        </div>
        <Button
          variant="ghost"
          size="sm"
          icon={<FiDownload />}
          onClick={() => {
            exportMealPlanPDF(mealPlan, preferences || undefined);
            toast.success('Meal plan saved as meal-plan.pdf');
          }}
        >
          Export PDF
        </Button>
      </div>

      <MealPlanForm
        preferences={preferences}
        isGenerating={isGenerating}
        onPreferencesChange={setPreferences}
        onSubmit={(e) => { e.preventDefault(); handleGenerate(); }}
        onPresetSelect={(query) => { setPreferences(query); handleGenerate(query); }}
      />

      {planError && (
        <ErrorState
          message={planError}
          title="Generation Failed"
          onRetry={() => handleGenerate(lastPref)}
          retryLabel="Try Again"
          onSecondary={() => setPlanError(null)}
          secondaryLabel="Use Sample Plan"
          icon={<FiRefreshCw />}
          className="planner-error"
        />
      )}

      <MealPlanDayTabs
        mealPlan={mealPlan}
        selectedDay={selectedDay}
        onSelectDay={setSelectedDay}
        getDayTotal={getDayTotal}
      />

      {selectedDayData && (
        <MealPlanDayDetail
          dayData={selectedDayData}
          getDayTotal={getDayTotal}
          getDayProtein={getDayProtein}
          onSlotClick={handleSlotClick}
        />
      )}

      <MealPlanWeekGrid
        mealPlan={mealPlan}
        selectedDay={selectedDay}
        onSelectDay={setSelectedDay}
        onSlotClick={handleSlotClick}
        getDayTotal={getDayTotal}
      />
    </PageWrapper>
  );
};

export default MealPlanner;
