import jsPDF from 'jspdf';
import type { MealPlanDay } from '@/types';

const ORANGE: [number, number, number] = [232, 137, 74];
const WARM_BG: [number, number, number] = [245, 239, 230];
const DARK: [number, number, number] = [30, 30, 30];
const MUTED: [number, number, number] = [130, 100, 65];
const LIGHT_MUTED: [number, number, number] = [160, 140, 120];

const SLOTS = [
  { key: 'breakfast', label: 'Breakfast' },
  { key: 'lunch', label: 'Lunch' },
  { key: 'dinner', label: 'Dinner' },
  { key: 'snack', label: 'Snack' },
] as const;

export function exportMealPlanPDF(mealPlan: MealPlanDay[], preferences?: string): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 16;
  const contentW = pageW - margin * 2;

  // ── Header banner ──────────────────────────────────────────────────
  doc.setFillColor(...ORANGE);
  doc.rect(0, 0, pageW, 30, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('Weekly Meal Plan', margin, 13);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const subtitle = preferences ? `Preferences: ${preferences}` : 'Generated by Chef AI Copilot';
  doc.text(subtitle, margin, 23);

  let y = 40;

  // ── Days ────────────────────────────────────────────────────────────
  for (const day of mealPlan) {
    if (y > 252) {
      doc.addPage();
      y = 18;
    }

    // Day row
    doc.setFillColor(...WARM_BG);
    doc.roundedRect(margin, y, contentW, 8, 2, 2, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...DARK);
    doc.text(day.day, margin + 4, y + 5.6);

    const totalCal =
      (day.breakfast?.calories ?? 0) +
      (day.lunch?.calories ?? 0) +
      (day.dinner?.calories ?? 0);
    const totalProt =
      (day.breakfast?.protein ?? 0) +
      (day.lunch?.protein ?? 0) +
      (day.dinner?.protein ?? 0);

    if (totalCal) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      const summary = `${totalCal} kcal  •  ${totalProt}g protein`;
      const sw = doc.getTextWidth(summary);
      doc.text(summary, pageW - margin - sw, y + 5.6);
    }

    y += 11;

    // Meal slots
    for (const { key, label } of SLOTS) {
      const recipe = day[key];
      if (!recipe) continue;

      if (y > 272) {
        doc.addPage();
        y = 18;
      }

      // Label pill
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(...ORANGE);
      doc.text(label.toUpperCase(), margin + 2, y + 4.2);

      // Recipe name
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.setTextColor(...DARK);
      const nameX = margin + 22;
      const nameLines = doc.splitTextToSize(recipe.title, contentW - 22);
      doc.text(nameLines, nameX, y + 4.2);

      // Meta row
      const meta: string[] = [];
      if (recipe.calories) meta.push(`${recipe.calories} kcal`);
      if (recipe.protein) meta.push(`${recipe.protein}g protein`);
      if (recipe.cookingTime) meta.push(`${recipe.cookingTime} min`);
      if (recipe.difficulty) meta.push(recipe.difficulty);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(...MUTED);
      doc.text(meta.join('  •  '), nameX, y + 9.5);

      y += 13;
    }

    y += 4;
  }

  // ── Page footers ───────────────────────────────────────────────────
  const totalPages = (doc.internal as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(...LIGHT_MUTED);
    doc.text(
      `Chef AI Copilot  •  Page ${i} of ${totalPages}`,
      pageW / 2,
      291,
      { align: 'center' }
    );
  }

  doc.save('meal-plan.pdf');
}
